### PR TITLE
[fix] local builds don't have buildtype set

### LINKED ISSUE #1247: local builds don't have buildtype set
**Describe the bug**
Running rpminspect on locally downloaded builds don't set the build type on them. This causes that inspections that rely on that are skipped.
Local module builds will skip `modularity` inspection reporting "`Inspection skipped because this build's type is not module`", 
Rpm builds will skip `changelog` inspection reporting "`Inspection skipped because this build's type is not rpm` "

**To Reproduce**
```
$ mkdir ~/builds
$ rpminspect-redhat -f -w ~/builds -a src llvm-toolset-rhel8-8090020230803191529.b46abd14
$ rpminspect-redhat -T modularity -a src ~/builds/llvm-toolset-rhel8-8090020230803191529.b46abd14/
[...]
modularity:                                                         
-----------                                                         
1) Inspection skipped because this build's type is not `module'.    
                                                                    
Result: INFO                                                        
Waiver Authorization: Not Waivable                
[...]
```

**Expected behavior**
rpminspect should run inspections in local builds correctly, depending on which kind of build they are.

### PR DESCRIPTION
**Pull request by jchecahi**
Add an additional check in gather_local_build function to infer which type of build we are testing. This prevents some inspections to be skipped, as they need to know the buildtype.

This PR aims to fix #1247

### CODE REVIEW

File: lib/builds.c [hunk 1]
```diff
@@ -799,6 +801,20 @@ static int gather_local_build(const char *build)
 
     set_worksubdir(workri, LOCAL_WORKDIR, NULL, NULL);
 
+    /*
+     * Some inspections need to know which kind of build are testing. Remote
+     * builds know this from the metadata provided by Koji. For local builds, we
+     * need to tell it by the presence of the modulemd file.
+     */
+    modulemd_path = strdup(build);
+    modulemd_path = strappend(modulemd_path, "/files/", MODULEMD_FILENAME, NULL);
```
Comment (dcantrell) [inline lib/builds.c:810]: Can you place a blank line between lines 810 and 811?

File: lib/builds.c [hunk 2]
```diff
@@ -799,6 +801,20 @@ static int gather_local_build(const char *build)
...
+    if (access(modulemd_path, F_OK) == 0){
+        ri->buildtype = KOJI_BUILD_MODULE;
+    } else{
+        ri->buildtype = KOJI_BUILD_RPM;
+    }
+    free(modulemd_path);
```
Comment (dcantrell) [inline lib/builds.c:816]: Can you place a blank line between lines 815 and 816?

**Review by dcantrell — CHANGES_REQUESTED** [review]
Looks good, just some formatting change requests.  Thanks.
